@startuml model

class GrainSilo {
  id: Integer
  capacity: Litre
  occupancy: Litre
  mass: Gram
  relativeHumidity: Percent
  temperature: Kelvin
}

class TargetSiloState {
  id: Integer
  scheduled: DateTime
  mass: Gram
  relativeHumidity: Percent
  temperature: Kelvin 
}

TargetSiloState --> GrainSilo

@enduml